### ISSUE TITLE
Vizualisation tool (graph / node view) ?

### ISSUE THREAD

**Issue by ssinfod** [samatt/airoViz#8]
Hello, 

Can you tell me what tool/framework that you have used to show the graph/node in your video ?
https://vimeo.com/98617656

I mean the graph with the red/blue node.
Is the code to build the graph included in your airoViz github project ?

I'm quickly going over the files in the repository but I can see where you are doing the graph...

Can you tell me how you are making the graph and what tool are used to make it ?

Thanks for your time,

**Comment by samatt** [comment]
Hey @ssinfod,

The viz you're looking for is here now: 
https://github.com/samatt/NSHeyy-Viz

Its pretty old and I havent updated it in a while but the actual d3 graph code is here:
https://github.com/samatt/NSHeyy-Viz/blob/master/nw/app/scripts/graph.js

**Comment by ssinfod** [comment]
thanks for your answer. I also found the code for the graph here: https://github.com/samatt/airoViz/tree/master/calibration

thanks
